version: "3.9"
networks:
  prjctnet:

services:
  ###########
  ## Proxy ##
  ###########
  proxy:
    image: harbor.cubexs.dev/prjctrepo/proxy
    ports:
      - 80:8080
    networks:
      - prjctnet

  ##################
  ## Dependencies ##
  ##################

  postgres:
    image: postgres:14.5-alpine3.16
    environment:
      - POSTGRES_PASSWORD=prjctdb
      - POSTGRES_USER=prjctdb
      - PGDATA=/var/lib/postgresql/data/db
    ports:
      - 5432:5432
    networks:
      - prjctnet
