version: "3.9"
networks:
  prjctnet:

services:
  ##################
  ## Dependencies ##
  ##################

  postgres:
    image: postgres:14.5-alpine3.16
    environment:
      - POSTGRES_PASSWORD=local
      - POSTGRES_USER=local
      - PGDATA=/var/lib/postgresql/data/db
    ports:
      - 5432:5432
    networks:
      - prjctnet
