version: "3.9"
networks:
  prjct:

services:
  ###########
  ## Proxy ##
  ###########
  proxy:
    image: harbor.cubexs.dev/prjct/proxy
    ports:
      - 80:8080
    networks:
      - prjct

  ##################
  ## Dependencies ##
  ##################

  postgres:
    image: postgres:14.3-alpine3.16
    environment:
      - POSTGRES_PASSWORD=prjct
      - POSTGRES_USER=prjct
      - PGDATA=/var/lib/postgresql/data/db
    ports:
      - 5432:5432
